version: '3.5'
services:
  database:
    container_name: jeopardy_database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
        - jeopardypgdata:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: jeopardy_dev
volumes:
    jeopardypgdata:
